In [1]:
import numpy as np

## Numpy array

In [2]:
benimListem=[20,30,40]

In [3]:
np.array(benimListem)

array([20, 30, 40])

In [4]:
matrixListesi=[[10,20,30],[20,30,40],[50,60,40]]

In [5]:
type(matrixListesi)

list

In [6]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [50, 60, 40]])

## arange

In [7]:
list(range(0,10,))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

## zeros

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [12]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

## linspace

In [13]:
np.linspace(1,100,100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [14]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [15]:
## önemli bir komut bilinmesi gerekiyor.

In [16]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [17]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random


In [19]:
np.random.randn(3)

array([ 0.69814913, -0.04434703,  1.5650819 ])

In [20]:
np.random.randn(2,2)

array([[-0.54423468,  0.29219012],
       [ 0.91495332, -0.88983004]])

In [21]:
np.random.randint(0,20)

1

In [22]:
np.random.randint(1,400,4)

array([315, 117, 391,  20])

In [23]:
benimNumpyDizim=np.arange(0,30)

In [24]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
benimRandomDizim=np.random.randint(0,500,4)

In [26]:
benimRandomDizim

array([194, 395, 192, 180])

## numpy dizi methodları

In [39]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [28]:
benimNumpyDizim.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [29]:
benimRandomDizim.max()

395

In [30]:
benimRandomDizim.min()

180

In [31]:
benimRandomDizim.argmax()

1

In [32]:
benimRandomDizim.argmin()

3

In [33]:
benimRandomDizim.shape

(4,)

In [34]:
benimRandomDizim.reshape(2,2)

array([[194, 395],
       [192, 180]])

In [35]:
benimRandomDizim

array([194, 395, 192, 180])

In [36]:
benimRandomDizimReshape=benimRandomDizim.reshape(2,2)

In [37]:
benimRandomDizimReshape

array([[194, 395],
       [192, 180]])

In [38]:
benimRandomDizimReshape.shape

(2, 2)