In [1]:
import numpy as np

In [2]:
benimDizi=np.arange(0,15)

In [3]:
benimDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimDizi[5]

5

In [6]:
benimDizi[3:5]

array([3, 4])

In [7]:
benimDizi[3:5]=15

In [8]:
benimDizi

array([ 0,  1,  2, 15, 15,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
baskaDizi=np.arange(0,24)

In [10]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
slicingdizisi=baskaDizi[3:6]

In [14]:
slicingdizisi

array([3, 4, 5])

In [15]:
slicingdizisi[:]=100

In [16]:
slicingdizisi

array([100, 100, 100])

In [17]:
baskaDizi

array([  0,   1,   2, 100, 100, 100,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [18]:
ornekDizi=np.arange(0,24)

In [19]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
ornekDiziKopyası=ornekDizi.copy()

In [21]:
ornekDiziKopyası

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
ornekDiziKopyasıSlicing=ornekDiziKopyası[3:6]

In [24]:
ornekDiziKopyasıSlicing[:]=500

In [25]:
ornekDiziKopyasıSlicing

array([500, 500, 500])

In [26]:
ornekDiziKopyası

array([  0,   1,   2, 500, 500, 500,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [27]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## MATRİX

In [28]:
benimListem=[[10,20,30],[20,30,40],[40,50,60]]

In [31]:
matrixDizim=np.array(benimListem)

In [32]:
matrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [33]:
matrixDizim[0][1]

20

In [35]:
matrixDizim[2]

array([40, 50, 60])

In [38]:
matrixDizim[0:,1]

array([20, 30, 50])

In [39]:
matrixDizim[1:,0]

array([20, 40])

In [40]:
yeniListe=[[1,2,3,4],[5,6,7,8],[5,6,7,8,],[10,11,12,13],[20,21,22,23]]

In [41]:
matrix=np.array(yeniListe)

In [42]:
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [44]:
matrix[2]

array([5, 6, 7, 8])

In [45]:
matrix[[0,2,4]]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [20, 21, 22, 23]])

## Operasyonlar

In [46]:
yeniBirDizi=np.random.randint(1,100,20)

In [47]:
yeniBirDizi

array([34, 70,  6, 80, 40, 20,  8, 95, 68, 23, 36, 87, 26, 47, 75, 69,  3,
       86, 64, 60])

In [48]:
yeniBirDizi>24

array([ True,  True, False,  True,  True, False, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True])

In [49]:
yeniBirDizi

array([34, 70,  6, 80, 40, 20,  8, 95, 68, 23, 36, 87, 26, 47, 75, 69,  3,
       86, 64, 60])

In [50]:
sonucDizisi=yeniBirDizi>24

In [51]:
sonucDizisi

array([ True,  True, False,  True,  True, False, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True])

In [52]:
yeniBirDizi[sonucDizisi]

array([34, 70, 80, 40, 95, 68, 36, 87, 26, 47, 75, 69, 86, 64, 60])

In [53]:
## sadece trueları filtreledim

In [54]:
sonDizi=np.arange(0,24)

In [55]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [56]:
sonDizi+sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [57]:
sonDizi-sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [58]:
sonDizi*sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [59]:
sonDizi/sonDizi

<ipython-input-59-7d5697280f2b>:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi/sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [62]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [63]:
## karekök aldık

In [64]:
np.max(sonDizi)

23

In [65]:
np.min(sonDizi)

0